# Generated by Django 2.2.5 on 2021-01-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210125_0057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': '사진'},
        ),
    ]
